### ISSUE TITLE
Version lockdown

### ISSUE THREAD

**Issue by e-stankevicius** [jpcaparas/docker-web-stack#3]
If you had version lockdown on packages, you could have some good production container too.

**Comment by jpcaparas** [comment]
Hi man, thanks for the suggestion.

By _version lockdown_ do you mean keeping the image versions intact until a next major release of the repo?

**Comment by e-stankevicius** [comment]
Version lockdown for apt-get install

**Comment by jpcaparas** [comment]
Cool, I'll add you as a reviewer on my next PR. :)
